<b>Phishing Classification</b>

1.<u>Data preprocessing</i>

<i>Importing modules</i>

In [2]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns

<i>Importing dataset</i>

In [3]:
dataset=pd.read_csv(r"C:\Users\HP\OneDrive\Desktop\PHISHINGWEB\url.csv")

<i>Information about the dataset</i>

In [4]:
dataset.info()

<class 'pandas.DataFrame'>
RangeIndex: 235795 entries, 0 to 235794
Data columns (total 56 columns):
 #   Column                      Non-Null Count   Dtype  
---  ------                      --------------   -----  
 0   FILENAME                    235795 non-null  str    
 1   URL                         235795 non-null  str    
 2   URLLength                   235795 non-null  int64  
 3   Domain                      235795 non-null  str    
 4   DomainLength                235795 non-null  int64  
 5   IsDomainIP                  235795 non-null  int64  
 6   TLD                         235795 non-null  str    
 7   URLSimilarityIndex          235795 non-null  float64
 8   CharContinuationRate        235795 non-null  float64
 9   TLDLegitimateProb           235795 non-null  float64
 10  URLCharProb                 235795 non-null  float64
 11  TLDLength                   235795 non-null  int64  
 12  NoOfSubDomain               235795 non-null  int64  
 13  HasObfuscation           

<i>First 5 rows</i>

In [5]:
dataset.head()

,FILENAME,URL,URLLength,Domain,DomainLength,IsDomainIP,TLD,URLSimilarityIndex,CharContinuationRate,TLDLegitimateProb,...,Pay,Crypto,HasCopyrightInfo,NoOfImage,NoOfCSS,NoOfJS,NoOfSelfRef,NoOfEmptyRef,NoOfExternalRef,label
0,521848.txt,https://www.southbankmosaics.com,31,www.southbankmosaics.com,24,0,com,100.0,1.000000,0.522907,...,0,0,1,34,20,28,119,0,124,1
1,31372.txt,https://www.uni-mainz.de,23,www.uni-mainz.de,16,0,de,100.0,0.666667,0.032650,...,0,0,1,50,9,8,39,0,217,1
2,597387.txt,https://www.voicefmradio.co.uk,29,www.voicefmradio.co.uk,22,0,uk,100.0,0.866667,0.028555,...,0,0,1,10,2,7,42,2,5,1
3,554095.txt,https://www.sfnmjournal.com,26,www.sfnmjournal.com,19,0,com,100.0,1.000000,0.522907,...,1,1,1,3,27,15,22,1,31,1
4,151578.txt,https://www.rewildingargentina.org,33,www.rewildingargentina.org,26,0,org,100.0,1.000000,0.079963,...,1,0,1,244,15,34,72,1,85,1


<i>Last 5 rows</i>

In [6]:
dataset.tail()

,FILENAME,URL,URLLength,Domain,DomainLength,IsDomainIP,TLD,URLSimilarityIndex,CharContinuationRate,TLDLegitimateProb,...,Pay,Crypto,HasCopyrightInfo,NoOfImage,NoOfCSS,NoOfJS,NoOfSelfRef,NoOfEmptyRef,NoOfExternalRef,label
235790,660997.txt,https://www.skincareliving.com,29,www.skincareliving.com,22,0,com,100.000000,1.000000,0.522907,...,1,0,1,51,7,21,187,2,191,1
235791,77185.txt,https://www.winchester.gov.uk,28,www.winchester.gov.uk,21,0,uk,100.000000,0.785714,0.028555,...,1,0,0,50,1,7,88,0,31,1
235792,622132.txt,https://www.nononsensedesign.be,30,www.nononsensedesign.be,23,0,be,100.000000,1.000000,0.003319,...,0,0,1,27,10,30,58,2,67,1
235793,7503962.txt,https://patient-cell-40f5.updatedlogmylogin.wo...,55,patient-cell-40f5.updatedlogmylogin.workers.dev,47,0,dev,28.157537,0.465116,0.000961,...,0,0,0,0,0,3,0,0,0,0
235794,384822.txt,https://www.alternativefinland.com,33,www.alternativefinland.com,26,0,com,100.000000,1.000000,0.522907,...,0,0,1,21,6,18,256,0,261,1


<i>Understanding missing values</i>

In [7]:
print("Number of missing values:")
print(dataset.isnull().sum())
print()

print("Percentage number of missing values:")
print(dataset.isnull().sum()/len(dataset)*100)

Number of missing values:
FILENAME                      0
URL                           0
URLLength                     0
Domain                        0
DomainLength                  0
IsDomainIP                    0
TLD                           0
URLSimilarityIndex            0
CharContinuationRate          0
TLDLegitimateProb             0
URLCharProb                   0
TLDLength                     0
NoOfSubDomain                 0
HasObfuscation                0
NoOfObfuscatedChar            0
ObfuscationRatio              0
NoOfLettersInURL              0
LetterRatioInURL              0
NoOfDegitsInURL               0
DegitRatioInURL               0
NoOfEqualsInURL               0
NoOfQMarkInURL                0
NoOfAmpersandInURL            0
NoOfOtherSpecialCharsInURL    0
SpacialCharRatioInURL         0
IsHTTPS                       0
LineOfCode                    0
LargestLineLength             0
HasTitle                      0
Title                         0
DomainTitleMat

<i>Dropping unnecessary columns</i>

Dropped URL and Domain because of URLSimilarityIndex.

Dropped FILENAME because not important

In [8]:
dataset=dataset.drop(["URL","Domain","FILENAME","Title"],axis="columns")

- Updated dataset

In [9]:
dataset.head()

,URLLength,DomainLength,IsDomainIP,TLD,URLSimilarityIndex,CharContinuationRate,TLDLegitimateProb,URLCharProb,TLDLength,NoOfSubDomain,...,Pay,Crypto,HasCopyrightInfo,NoOfImage,NoOfCSS,NoOfJS,NoOfSelfRef,NoOfEmptyRef,NoOfExternalRef,label
0,31,24,0,com,100.0,1.000000,0.522907,0.061933,3,1,...,0,0,1,34,20,28,119,0,124,1
1,23,16,0,de,100.0,0.666667,0.032650,0.050207,2,1,...,0,0,1,50,9,8,39,0,217,1
2,29,22,0,uk,100.0,0.866667,0.028555,0.064129,2,2,...,0,0,1,10,2,7,42,2,5,1
3,26,19,0,com,100.0,1.000000,0.522907,0.057606,3,1,...,1,1,1,3,27,15,22,1,31,1
4,33,26,0,org,100.0,1.000000,0.079963,0.059441,3,1,...,1,0,1,244,15,34,72,1,85,1


Dropping columns due to ANOVA test

In [10]:
import statsmodels.api as sm
from statsmodels.formula.api import ols

numeric_col=dataset.select_dtypes(["int64","float64"]).columns

for col in numeric_col:
    if col!="label":
        model=ols(f"label~Q('{col}')",data=dataset).fit()
        anova=sm.stats.anova_lm(model,typ=2)
        print(f"Anova result for {col}:")
        print(anova)
        print()

Anova result for URLLength:
                      sum_sq        df             F  PR(>F)
Q('URLLength')   3146.086084       1.0  13590.556633     0.0
Residual        54583.862601  235793.0           NaN     NaN

Anova result for DomainLength:
                         sum_sq        df             F  PR(>F)
Q('DomainLength')   4628.498214       1.0  20552.498467     0.0
Residual           53101.450470  235793.0           NaN     NaN

Anova result for IsDomainIP:
                       sum_sq        df           F         PR(>F)
Q('IsDomainIP')    209.232950       1.0  857.702556  3.355307e-188
Residual         57520.715735  235793.0         NaN            NaN

Anova result for URLSimilarityIndex:
                               sum_sq        df              F  PR(>F)
Q('URLSimilarityIndex')  42732.628715       1.0  671857.021355     0.0
Residual                 14997.319969  235793.0            NaN     NaN

Anova result for CharContinuationRate:
                                 sum_sq    

- Dropping columns to reduce correlation

In [11]:
dataset=dataset.drop(["URLSimilarityIndex","HasTitle","DomainTitleMatchScore","URLTitleMatchScore","HasFavicon","Robots","IsResponsive","NoOfURLRedirect","NoOfSelfRedirect","HasDescription","HasSocialNet","HasCopyrightInfo","NoOfPopup","NoOfiFrame","HasExternalFormSubmit","HasSubmitButton","HasHiddenFields","HasPasswordField","LineOfCode","LargestLineLength","NoOfImage","NoOfCSS","NoOfJS","NoOfSelfRef","NoOfEmptyRef","NoOfExternalRef","IsHTTPS","Bank","Pay","Crypto"],axis="columns")

- Updated dataset

In [12]:
dataset.info()

<class 'pandas.DataFrame'>
RangeIndex: 235795 entries, 0 to 235794
Data columns (total 22 columns):
 #   Column                      Non-Null Count   Dtype  
---  ------                      --------------   -----  
 0   URLLength                   235795 non-null  int64  
 1   DomainLength                235795 non-null  int64  
 2   IsDomainIP                  235795 non-null  int64  
 3   TLD                         235795 non-null  str    
 4   CharContinuationRate        235795 non-null  float64
 5   TLDLegitimateProb           235795 non-null  float64
 6   URLCharProb                 235795 non-null  float64
 7   TLDLength                   235795 non-null  int64  
 8   NoOfSubDomain               235795 non-null  int64  
 9   HasObfuscation              235795 non-null  int64  
 10  NoOfObfuscatedChar          235795 non-null  int64  
 11  ObfuscationRatio            235795 non-null  float64
 12  NoOfLettersInURL            235795 non-null  int64  
 13  LetterRatioInURL         

<i>Encoding categorical variables</i>

In [13]:
dataset["TLD"].nunique()

695

Checking whether to drop TLD

In [14]:
dataset["TLDLegitimateProb"]

0         0.522907
1         0.032650
2         0.028555
3         0.522907
4         0.079963
            ...   
235790    0.522907
235791    0.028555
235792    0.003319
235793    0.000961
235794    0.522907
Name: TLDLegitimateProb, Length: 235795, dtype: float64

If the value comes out to be 1, then we can drop TLD

In [15]:
print(dataset.groupby("TLD")["TLDLegitimateProb"].nunique().max())

1


Therefore we can drop TLD

In [16]:
dataset=dataset.drop(["TLD"],axis="columns")

- Updated dataset

In [17]:
dataset.info()

<class 'pandas.DataFrame'>
RangeIndex: 235795 entries, 0 to 235794
Data columns (total 21 columns):
 #   Column                      Non-Null Count   Dtype  
---  ------                      --------------   -----  
 0   URLLength                   235795 non-null  int64  
 1   DomainLength                235795 non-null  int64  
 2   IsDomainIP                  235795 non-null  int64  
 3   CharContinuationRate        235795 non-null  float64
 4   TLDLegitimateProb           235795 non-null  float64
 5   URLCharProb                 235795 non-null  float64
 6   TLDLength                   235795 non-null  int64  
 7   NoOfSubDomain               235795 non-null  int64  
 8   HasObfuscation              235795 non-null  int64  
 9   NoOfObfuscatedChar          235795 non-null  int64  
 10  ObfuscationRatio            235795 non-null  float64
 11  NoOfLettersInURL            235795 non-null  int64  
 12  LetterRatioInURL            235795 non-null  float64
 13  NoOfDegitsInURL          

<i>Understanding outliers</i>

- Separating non-binary columns

In [18]:
binary_cols = [col for col in dataset.select_dtypes(["int64", "float64"]).columns 
               if dataset[col].nunique() == 2]
continuous_cols = [col for col in dataset.select_dtypes(["int64", "float64"]).columns 
                    if col not in binary_cols and col != "label"]

- Finding outliers

In [19]:
for col in continuous_cols:
    q1=dataset[col].quantile(0.25)
    q3=dataset[col].quantile(0.75)
    iqr=q3-q1
    lower=q1-1.5*iqr
    upper=q3+1.5*iqr
    outliers=((dataset[col]<lower)|(dataset[col]>upper))
    print(f"For {col}:",outliers.sum()/len(dataset)*100)

For URLLength: 9.539218388854726
For DomainLength: 5.714285714285714
For CharContinuationRate: 0.2879620008906041
For TLDLegitimateProb: 0.0
For URLCharProb: 3.634088933183486
For TLDLength: 0.9050234313704701
For NoOfSubDomain: 24.338514387497614
For NoOfObfuscatedChar: 0.20568714349328865
For ObfuscationRatio: 0.20568714349328865
For NoOfLettersInURL: 8.33859920693823
For LetterRatioInURL: 0.600945736762866
For NoOfDegitsInURL: 21.824466167645625
For DegitRatioInURL: 21.824466167645625
For NoOfEqualsInURL: 2.2905489938293857
For NoOfQMarkInURL: 2.599715854873937
For NoOfAmpersandInURL: 0.37617421913102483
For NoOfOtherSpecialCharsInURL: 5.250323374117348
For SpacialCharRatioInURL: 1.4181810470959944


<i>Handling outliers</i>

In [20]:
for col in continuous_cols:
    q1=dataset[col].quantile(0.25)
    q3=dataset[col].quantile(0.75)
    iqr=q3-q1
    lower=q1-1.5*iqr
    upper=q3+1.5*iqr
    dataset[col]=np.where(dataset[col]<lower,lower,np.where(dataset[col]>upper,upper,dataset[col]))
    outliers=((dataset[col]<lower)|(dataset[col]>upper))
    print(f"For {col}:",outliers.sum()/len(dataset)*100)

For URLLength: 0.0
For DomainLength: 0.0
For CharContinuationRate: 0.0
For TLDLegitimateProb: 0.0
For URLCharProb: 0.0
For TLDLength: 0.0
For NoOfSubDomain: 0.0
For NoOfObfuscatedChar: 0.0
For ObfuscationRatio: 0.0
For NoOfLettersInURL: 0.0
For LetterRatioInURL: 0.0
For NoOfDegitsInURL: 0.0
For DegitRatioInURL: 0.0
For NoOfEqualsInURL: 0.0
For NoOfQMarkInURL: 0.0
For NoOfAmpersandInURL: 0.0
For NoOfOtherSpecialCharsInURL: 0.0
For SpacialCharRatioInURL: 0.0


<i>Splitting the dataset into Matrix of Features (X) and Independent Variable (y)</i>

In [21]:
X=dataset.iloc[:,:-1].values
y=dataset.iloc[:,-1].values

<i>Splitting it into training and test set</i>

In [22]:
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=0)

<i>Feature scaling</i>

In [23]:
from sklearn.preprocessing import StandardScaler

feature_cols = dataset.drop("label", axis="columns").columns
continuous_indexes = [feature_cols.get_loc(col) for col in continuous_cols]
continuous_indexes = feature_cols.get_indexer(continuous_cols)

scaler=StandardScaler()
X_train[:, continuous_indexes] = scaler.fit_transform(X_train[:, continuous_indexes])
X_test[:, continuous_indexes] = scaler.transform(X_test[:, continuous_indexes])

2.<u>Model builiding</u>

<b>a. Logistic Regression</b>

<i>Model building</i>

In [24]:
from sklearn.linear_model import LogisticRegression

classifier1=LogisticRegression()
classifier1.fit(X_train,y_train)

,"penalty penalty: {'l1', 'l2', 'elasticnet', None}, default='l2'Specify the norm of the penalty:- `None`: no penalty is added;- `'l2'`: add an L2 penalty term and it is the default choice;- `'l1'`: add an L1 penalty term;- `'elasticnet'`: both L1 and L2 penalty terms are added... warning:: Some penalties may not work with some solvers. See the parameter `solver` below, to know the compatibility between the penalty and solver... versionadded:: 0.19 l1 penalty with SAGA solver (allowing 'multinomial' + L1).. deprecated:: 1.8 `penalty` was deprecated in version 1.8 and will be removed in 1.10. Use `l1_ratio` and `C` instead. `l1_ratio=0` for `penalty='l2'`, `l1_ratio=1` for `penalty='l1'`, `l1_ratio` set to any float between 0 and 1 for `penalty='elasticnet'`, and `C=np.inf` for `penalty=None`.",'deprecated'
,"C C: float, default=1.0Inverse of regularization strength; must be a positive float.Like in support vector machines, smaller values specify strongerregularization. `C=np.inf` results in unpenalized logistic regression.For a visual example on the effect of tuning the `C` parameterwith an L1 penalty, see::ref:`sphx_glr_auto_examples_linear_model_plot_logistic_path.py`.",1.0
,"l1_ratio l1_ratio: float, default=0.0The Elastic-Net mixing parameter, with `0 <= l1_ratio <= 1`. Setting`l1_ratio=1` gives a pure L1-penalty, setting `l1_ratio=0` a pure L2-penalty.Any value between 0 and 1 gives an Elastic-Net penalty of the form`l1_ratio * L1 + (1 - l1_ratio) * L2`... warning:: Certain values of `l1_ratio`, i.e. some penalties, may not work with some solvers. See the parameter `solver` below, to know the compatibility between the penalty and solver... versionchanged:: 1.8 Default value changed from None to 0.0... deprecated:: 1.8 `None` is deprecated and will be removed in version 1.10. Always use `l1_ratio` to specify the penalty type.",0.0
,"dual dual: bool, default=FalseDual (constrained) or primal (regularized, see also:ref:`this equation <regularized-logistic-loss>`) formulation. Dual formulationis only implemented for l2 penalty with liblinear solver. Prefer `dual=False`when n_samples > n_features.",False
,"tol tol: float, default=1e-4Tolerance for stopping criteria.",0.0001
,"fit_intercept fit_intercept: bool, default=TrueSpecifies if a constant (a.k.a. bias or intercept) should beadded to the decision function.",True
,"intercept_scaling intercept_scaling: float, default=1Useful only when the solver `liblinear` is usedand `self.fit_intercept` is set to `True`. In this case, `x` becomes`[x, self.intercept_scaling]`,i.e. a ""synthetic"" feature with constant value equal to`intercept_scaling` is appended to the instance vector.The intercept becomes``intercept_scaling * synthetic_feature_weight``... note:: The synthetic feature weight is subject to L1 or L2 regularization as all other features. To lessen the effect of regularization on synthetic feature weight (and therefore on the intercept) `intercept_scaling` has to be increased.",1
,"class_weight class_weight: dict or 'balanced', default=NoneWeights associated with classes in the form ``{class_label: weight}``.If not given, all classes are supposed to have weight one.The ""balanced"" mode uses the values of y to automatically adjustweights inversely proportional to class frequencies in the input dataas ``n_samples / (n_classes * np.bincount(y))``.Note that these weights will be multiplied with sample_weight (passedthrough the fit method) if sample_weight is specified... versionadded:: 0.17 *class_weight='balanced'*",None
,"random_state random_state: int, RandomState instance, default=NoneUsed when ``solver`` == 'sag', 'saga' or 'liblinear' to shuffle thedata. See :term:`Glossary <random_state>` for details.",None
,"solver solver: {'lbfgs', 'liblinear', 'newton-cg', 'newton-cholesky', 'sag', 'saga'}, default='lbfgs'Algorithm to use in the optimization problem. Default is 'lbfgs'.To choose a solver, you might want to consider the following aspects:- 'lbfgs' is a good default sol

<i>Predicting the values for training and test set</i>

In [25]:
y_pred_train1=classifier1.predict(X_train)
y_pred_test1=classifier1.predict(X_test)

print("For the training set:")
print("[Actual_observations Predicted_observations]")
print(np.concatenate((y_train.reshape(len(y_train),1),y_pred_train1.reshape(len(y_pred_train1),1)),axis=1))
print()

print("For the test set:")
print("[Actual_observations Predicted_observations]")
print(np.concatenate((y_test.reshape(len(y_test),1),y_pred_test1.reshape(len(y_pred_test1),1)),axis=1))

For the training set:
[Actual_observations Predicted_observations]
[[0 1]
 [0 0]
 [1 1]
 ...
 [0 0]
 [1 1]
 [0 0]]

For the test set:
[Actual_observations Predicted_observations]
[[0 1]
 [1 1]
 [1 1]
 ...
 [0 1]
 [0 0]
 [0 1]]


<i>Accuracy of the model</i>

In [26]:
from sklearn.metrics import accuracy_score, confusion_matrix

con_mat_lr_train=confusion_matrix(y_train,y_pred_train1)
con_mat_lr_test=confusion_matrix(y_test,y_pred_test1)

print("For the training set:")
print(f"[[True_Negative False_Positive]\t= {con_mat_lr_train[0]}")
print(f"[False_Negative True_Positive]]\t  {con_mat_lr_train[1]}")
print(f"Correct observations: {con_mat_lr_train[0][0]+con_mat_lr_train[1][1]}")
print(f"Incorrect observations: {con_mat_lr_train[0][1]+con_mat_lr_train[1][0]}")
print(f"Accuracy for the training set: {accuracy_score(y_train,y_pred_train1)*100}%")
print()

print("For the test set:")
print(f"[[True_Negative False_Positive]\t= {con_mat_lr_test[0]}")
print(f"[False_Negative True_Positive]]\t  {con_mat_lr_test[1]}")
print(f"Correct observations: {con_mat_lr_test[0][0]+con_mat_lr_test[1][1]}")
print(f"Incorrect observations: {con_mat_lr_test[0][1]+con_mat_lr_test[1][0]}")
print(f"Accuracy for the test set: {accuracy_score(y_test,y_pred_test1)*100}%")

For the training set:
[[True_Negative False_Positive]	= [59261 21484]
[False_Negative True_Positive]]	  [  5564 102327]
Correct observations: 161588
Incorrect observations: 27048
Accuracy for the training set: 85.66127356390083%

For the test set:
[[True_Negative False_Positive]	= [14784  5416]
[False_Negative True_Positive]]	  [ 1377 25582]
Correct observations: 40366
Incorrect observations: 6793
Accuracy for the test set: 85.5955384974236%


<i>Classification report</i>

In [27]:
from sklearn.metrics import classification_report

print("Classification report for the training set:")
print(classification_report(y_train,y_pred_train1))
print()

print("Classification report for the test set:")
print(classification_report(y_test,y_pred_test1))

Classification report for the training set:
              precision    recall  f1-score   support

           0       0.91      0.73      0.81     80745
           1       0.83      0.95      0.88    107891

    accuracy                           0.86    188636
   macro avg       0.87      0.84      0.85    188636
weighted avg       0.86      0.86      0.85    188636


Classification report for the test set:
              precision    recall  f1-score   support

           0       0.91      0.73      0.81     20200
           1       0.83      0.95      0.88     26959

    accuracy                           0.86     47159
   macro avg       0.87      0.84      0.85     47159
weighted avg       0.86      0.86      0.85     47159



<i>Cross-Validation</i>

In [28]:
from sklearn.model_selection import cross_val_score

cross_val1_lr_train=cross_val_score(classifier1,X_train,y_train,cv=10)

print("Training accuracy after cross-validation:",cross_val1_lr_train.mean()*100,"%")


Training accuracy after cross-validation: 85.65862491955183 %


<b>b. KNN</b>

<i>Model building</i>

In [29]:
from sklearn.neighbors import KNeighborsClassifier

classifier2=KNeighborsClassifier(n_neighbors=15,metric="minkowski",p=2)
classifier2.fit(X_train,y_train)

,"n_neighbors n_neighbors: int, default=5Number of neighbors to use by default for :meth:`kneighbors` queries.",15
,"weights weights: {'uniform', 'distance'}, callable or None, default='uniform'Weight function used in prediction. Possible values:- 'uniform' : uniform weights. All points in each neighborhood are weighted equally.- 'distance' : weight points by the inverse of their distance. in this case, closer neighbors of a query point will have a greater influence than neighbors which are further away.- [callable] : a user-defined function which accepts an array of distances, and returns an array of the same shape containing the weights.Refer to the example entitled:ref:`sphx_glr_auto_examples_neighbors_plot_classification.py`showing the impact of the `weights` parameter on the decisionboundary.",'uniform'
,"algorithm algorithm: {'auto', 'ball_tree', 'kd_tree', 'brute'}, default='auto'Algorithm used to compute the nearest neighbors:- 'ball_tree' will use :class:`BallTree`- 'kd_tree' will use :class:`KDTree`- 'brute' will use a brute-force search.- 'auto' will attempt to decide the most appropriate algorithm based on the values passed to :meth:`fit` method.Note: fitting on sparse input will override the setting ofthis parameter, using brute force.",'auto'
,"leaf_size leaf_size: int, default=30Leaf size passed to BallTree or KDTree. This can affect thespeed of the construction and query, as well as the memoryrequired to store the tree. The optimal value depends on thenature of the problem.",30
,"p p: float, default=2Power parameter for the Minkowski metric. When p = 1, this is equivalentto using manhattan_distance (l1), and euclidean_distance (l2) for p = 2.For arbitrary p, minkowski_distance (l_p) is used. This parameter is expectedto be positive.",2
,"metric metric: str or callable, default='minkowski'Metric to use for distance computation. Default is ""minkowski"", whichresults in the standard Euclidean distance when p = 2. See thedocumentation of `scipy.spatial.distance<https://docs.scipy.org/doc/scipy/reference/spatial.distance.html>`_ andthe metrics listed in:class:`~sklearn.metrics.pairwise.distance_metrics` for valid metricvalues.If metric is ""precomputed"", X is assumed to be a distance matrix andmust be square during fit. X may be a :term:`sparse graph`, in whichcase only ""nonzero"" elements may be considered neighbors.If metric is a callable function, it takes two arrays representing 1Dvectors as inputs and must return one value indicating the distancebetween those vectors. This works for Scipy's metrics, but is lessefficient than passing the metric name as a string.",'minkowski'
,"metric_params metric_params: dict, default=NoneAdditional keyword arguments for the metric function.",None
,"n_jobs n_jobs: int, default=NoneThe number of parallel jobs to run for neighbors search.``None`` means 1 unless in a :obj:`joblib.parallel_backend` context.``-1`` means using all processors. See :term:`Glossary <n_jobs>`for more details.Doesn't affect :meth:`fit` method.",None
Name,Type,Value
"classes_ classes_: array of shape (n_classes,)Class labels known to the classifier","ndarray[int64](2,)","[0,1]"
"effective_metric_ effective_metric_: str or callbleThe distance metric used. It will be same as the `metric` parameteror a synonym of it, e.g. 'euclidean' if the `metric` parameter set to'minkowski' and `p` parameter set to 2.",str,'eu...an'


<i>Predicting the values for training and test set</i>

In [30]:
y_pred_train2=classifier2.predict(X_train)
y_pred_test2=classifier2.predict(X_test)

print("For the training set:")
print("[Actual_observations Predicted_observations]")
print(np.concatenate((y_train.reshape(len(y_train),1),y_pred_train2.reshape(len(y_pred_train2),1)),axis=1))
print()

print("For the test set:")
print("[Actual_observations Predicted_observations]")
print(np.concatenate((y_test.reshape(len(y_test),1),y_pred_test2.reshape(len(y_pred_test2),1)),axis=1))

For the training set:
[Actual_observations Predicted_observations]
[[0 0]
 [0 0]
 [1 1]
 ...
 [0 0]
 [1 1]
 [0 0]]

For the test set:
[Actual_observations Predicted_observations]
[[0 0]
 [1 1]
 [1 1]
 ...
 [0 0]
 [0 0]
 [0 0]]


<i>Accuracy of the model</i>

In [31]:
from sklearn.metrics import accuracy_score, confusion_matrix

con_mat_knn_train=confusion_matrix(y_train,y_pred_train2)
con_mat_knn_test=confusion_matrix(y_test,y_pred_test2)

print("For the training set:")
print(f"[[True_Negative False_Positive]\t= {con_mat_knn_train[0]}")
print(f"[False_Negative True_Positive]]\t  {con_mat_knn_train[1]}")
print(f"Correct observations: {con_mat_lr_train[0][0]+con_mat_knn_train[1][1]}")
print(f"Incorrect observations: {con_mat_knn_train[0][1]+con_mat_knn_train[1][0]}")
print(f"Accuracy for the training set: {accuracy_score(y_train,y_pred_train2)*100}%")
print()

print("For the test set:")
print(f"[[True_Negative False_Positive]\t= {con_mat_knn_test[0]}")
print(f"[False_Negative True_Positive]]\t  {con_mat_knn_test[1]}")
print(f"Correct observations: {con_mat_knn_test[0][0]+con_mat_knn_test[1][1]}")
print(f"Incorrect observations: {con_mat_knn_test[0][1]+con_mat_knn_test[1][0]}")
print(f"Accuracy for the test set: {accuracy_score(y_test,y_pred_test2)*100}%")

For the training set:
[[True_Negative False_Positive]	= [76237  4508]
[False_Negative True_Positive]]	  [  1201 106690]
Correct observations: 165951
Incorrect observations: 5709
Accuracy for the training set: 96.97353633452788%

For the test set:
[[True_Negative False_Positive]	= [18882  1318]
[False_Negative True_Positive]]	  [  378 26581]
Correct observations: 45463
Incorrect observations: 1696
Accuracy for the test set: 96.40365571789053%


<i>Classification Report</i>

In [32]:
from sklearn.metrics import classification_report

print("Classification report for the training set:")
print(classification_report(y_train,y_pred_train2))
print()

print("Classification report for the test set:")
print(classification_report(y_test,y_pred_test2))

Classification report for the training set:
              precision    recall  f1-score   support

           0       0.98      0.94      0.96     80745
           1       0.96      0.99      0.97    107891

    accuracy                           0.97    188636
   macro avg       0.97      0.97      0.97    188636
weighted avg       0.97      0.97      0.97    188636


Classification report for the test set:
              precision    recall  f1-score   support

           0       0.98      0.93      0.96     20200
           1       0.95      0.99      0.97     26959

    accuracy                           0.96     47159
   macro avg       0.97      0.96      0.96     47159
weighted avg       0.96      0.96      0.96     47159



<b>c. Decision Tree Classifier</b>

<i>Model building</i>

In [33]:
from sklearn.tree import DecisionTreeClassifier

classifier3=DecisionTreeClassifier(criterion="entropy")
classifier3.fit(X_train,y_train)

,"criterion criterion: {""gini"", ""entropy"", ""log_loss""}, default=""gini""The function to measure the quality of a split. Supported criteria are""gini"" for the Gini impurity and ""log_loss"" and ""entropy"" both for theShannon information gain, see :ref:`tree_mathematical_formulation`.",'entropy'
,"splitter splitter: {""best"", ""random""}, default=""best""The strategy used to choose the split at each node. Supportedstrategies are ""best"" to choose the best split and ""random"" to choosethe best random split.",'best'
,"max_depth max_depth: int, default=NoneThe maximum depth of the tree. If None, then nodes are expanded untilall leaves are pure or until all leaves contain less thanmin_samples_split samples.",None
,"min_samples_split min_samples_split: int or float, default=2The minimum number of samples required to split an internal node:- If int, then consider `min_samples_split` as the minimum number.- If float, then `min_samples_split` is a fraction and `ceil(min_samples_split * n_samples)` are the minimum number of samples for each split... versionchanged:: 0.18 Added float values for fractions.",2
,"min_samples_leaf min_samples_leaf: int or float, default=1The minimum number of samples required to be at a leaf node.A split point at any depth will only be considered if it leaves atleast ``min_samples_leaf`` training samples in each of the left andright branches. This may have the effect of smoothing the model,especially in regression.- If int, then consider `min_samples_leaf` as the minimum number.- If float, then `min_samples_leaf` is a fraction and `ceil(min_samples_leaf * n_samples)` are the minimum number of samples for each node... versionchanged:: 0.18 Added float values for fractions.",1
,"min_weight_fraction_leaf min_weight_fraction_leaf: float, default=0.0The minimum weighted fraction of the sum total of weights (of allthe input samples) required to be at a leaf node. Samples haveequal weight when sample_weight is not provided.",0.0
,"max_features max_features: int, float or {""sqrt"", ""log2""}, default=NoneThe number of features to consider when looking for the best split:- If int, then consider `max_features` features at each split.- If float, then `max_features` is a fraction and `max(1, int(max_features * n_features_in_))` features are considered at each split.- If ""sqrt"", then `max_features=sqrt(n_features)`.- If ""log2"", then `max_features=log2(n_features)`.- If None, then `max_features=n_features`... note:: The search for a split does not stop until at least one valid partition of the node samples is found, even if it requires to effectively inspect more than ``max_features`` features.",None
,"random_state random_state: int, RandomState instance or None, default=NoneControls the randomness of the estimator. The features are alwaysrandomly permuted at each split, even if ``splitter`` is set to``""best""``. When ``max_features < n_features``, the algorithm willselect ``max_features`` at random at each split before finding the bestsplit among them. But the best found split may vary across differentruns, even if ``max_features=n_features``. That is the case, if theimprovement of the criterion is identical for several splits and onesplit has to be selected at random. To obtain a deterministic behaviourduring fitting, ``random_state`` has to be fixed to an integer.See :term:`Glossary <random_state>` for details.",None
,"max_leaf_nodes max_leaf_nodes: int, default=NoneGrow a tree with ``max_leaf_nodes`` in best-first fashion.Best nodes are defined as relative reduction in impurity.If None then unlimited number of leaf nodes.",None
,"min_impurity_decrease min_impurity_decrease: float, default=0.0A node will be split if this split induces a decrease of the impuritygreater than or equal to this value.The weighted impurity decrease equation is the following:: N_t / N * (impurity - N_t_R / N_t * right_impurity - N_t_L / N_t * left_impurity)where ``N`` is the total number of samples, ``N_t`` is the number ofsam

<i>Predicting values for training and test set</i>

In [34]:
y_pred_train3=classifier3.predict(X_train)
y_pred_test3=classifier3.predict(X_test)

print("For the training set:")
print("[Actual_observations Predicted_observations]")
print(np.concatenate((y_train.reshape(len(y_train),1),y_pred_train3.reshape(len(y_pred_train3),1)),axis=1))
print()

print("For the test set:")
print("[Actual_observations Predicted_observations]")
print(np.concatenate((y_test.reshape(len(y_test),1),y_pred_test3.reshape(len(y_pred_test3),1)),axis=1))

For the training set:
[Actual_observations Predicted_observations]
[[0 0]
 [0 0]
 [1 1]
 ...
 [0 0]
 [1 1]
 [0 0]]

For the test set:
[Actual_observations Predicted_observations]
[[0 0]
 [1 1]
 [1 1]
 ...
 [0 0]
 [0 0]
 [0 0]]


<i>Accuracy of the model</i>

In [35]:
from sklearn.metrics import accuracy_score, confusion_matrix

con_mat_tree_train=confusion_matrix(y_train,y_pred_train3)
con_mat_tree_test=confusion_matrix(y_test,y_pred_test3)

print("For the training set:")
print(f"[[True_Negative False_Positive]\t= {con_mat_tree_train[0]}")
print(f"[False_Negative True_Positive]]\t  {con_mat_tree_train[1]}")
print(f"Correct observations: {con_mat_tree_train[0][0]+con_mat_tree_train[1][1]}")
print(f"Incorrect observations: {con_mat_tree_train[0][1]+con_mat_tree_train[1][0]}")
print(f"Accuracy for the training set: {accuracy_score(y_train,y_pred_train3)*100}%")
print()

print("For the test set:")
print(f"[[True_Negative False_Positive]\t= {con_mat_tree_test[0]}")
print(f"[False_Negative True_Positive]]\t  {con_mat_tree_test[1]}")
print(f"Correct observations: {con_mat_tree_test[0][0]+con_mat_tree_test[1][1]}")
print(f"Incorrect observations: {con_mat_tree_test[0][1]+con_mat_tree_test[1][0]}")
print(f"Accuracy for the test set: {accuracy_score(y_test,y_pred_test3)*100}%")

For the training set:
[[True_Negative False_Positive]	= [80741     4]
[False_Negative True_Positive]]	  [    12 107879]
Correct observations: 188620
Incorrect observations: 16
Accuracy for the training set: 99.99151805593843%

For the test set:
[[True_Negative False_Positive]	= [19839   361]
[False_Negative True_Positive]]	  [  312 26647]
Correct observations: 46486
Incorrect observations: 673
Accuracy for the test set: 98.57291291163935%


<i>Classification Report</i>

In [36]:
from sklearn.metrics import classification_report

print("Classification report for the training set:")
print(classification_report(y_train,y_pred_train3))
print()

print("Classification report for the test set:")
print(classification_report(y_test,y_pred_test3))

Classification report for the training set:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     80745
           1       1.00      1.00      1.00    107891

    accuracy                           1.00    188636
   macro avg       1.00      1.00      1.00    188636
weighted avg       1.00      1.00      1.00    188636


Classification report for the test set:
              precision    recall  f1-score   support

           0       0.98      0.98      0.98     20200
           1       0.99      0.99      0.99     26959

    accuracy                           0.99     47159
   macro avg       0.99      0.99      0.99     47159
weighted avg       0.99      0.99      0.99     47159



<i>Cross-validation</i>

In [37]:
from sklearn.model_selection import cross_val_score

cross_val1_tree_train=cross_val_score(classifier3,X_train,y_train,cv=10)

print("Training accuracy after cross-validation:",cross_val1_tree_train.mean()*100,"%")


Training accuracy after cross-validation: 98.55117815945042 %


<b>c. Random Forest Classifier</b>

In [38]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
medium_forest = RandomForestClassifier(
    n_estimators=100,
    max_depth=15,
    criterion="gini",
    random_state=0,
    n_jobs=-1
)

medium_forest.fit(X_train, y_train)

y_pred_medium = medium_forest.predict(X_test)

print("Accuracy:", accuracy_score(y_test, y_pred_medium))

Accuracy: 0.9768230878517357


In [39]:
import pickle
import os

with open("Random_Forest_medium.pk", "wb") as f:
    pickle.dump(medium_forest, f)

size_mb = os.path.getsize("Random_Forest_medium.pk") / (1024 * 1024)

print(f"Model size: {size_mb:.2f} MB")


Model size: 22.83 MB


In [40]:
import pickle

with open("Random_Forest_medium.pk", "rb") as f:
    test_model = pickle.load(f)

print("Model loaded:", type(test_model).__name__)
print("Trees:", len(test_model.estimators_))
print("Depth:", test_model.max_depth)

Model loaded: RandomForestClassifier
Trees: 100
Depth: 15


<i>Model building</i>

In [41]:
'''from sklearn.ensemble import RandomForestClassifier

classifier4=RandomForestClassifier(n_estimators=500,criterion="gini")
classifier4.fit(X_train,y_train)'''

'from sklearn.ensemble import RandomForestClassifier\n\nclassifier4=RandomForestClassifier(n_estimators=500,criterion="gini")\nclassifier4.fit(X_train,y_train)'

<i>Predicting the values for training and test set</i>

In [42]:
y_pred_train_medium = medium_forest.predict(X_train)

y_pred_test_medium = medium_forest.predict(X_test)

print("For the training set:")

print("[Actual_observations Predicted_observations]")

print(np.concatenate((
    y_train.reshape(len(y_train),1),
    y_pred_train_medium.reshape(len(y_pred_train_medium),1)
), axis=1))

print()

print("For the test set:")

print("[Actual_observations Predicted_observations]")

print(np.concatenate((
    y_test.reshape(len(y_test),1),
    y_pred_test_medium.reshape(len(y_pred_test_medium),1)
), axis=1))

For the training set:
[Actual_observations Predicted_observations]
[[0 0]
 [0 0]
 [1 1]
 ...
 [0 0]
 [1 1]
 [0 0]]

For the test set:
[Actual_observations Predicted_observations]
[[0 0]
 [1 1]
 [1 1]
 ...
 [0 0]
 [0 0]
 [0 1]]


<i>Accuracy of the model</i>

In [43]:
from sklearn.metrics import accuracy_score, confusion_matrix

con_mat_forest_train = confusion_matrix(y_train, y_pred_train_medium)

con_mat_forest_test = confusion_matrix(y_test, y_pred_test_medium)

print("For the training set:")

print(f"[[True_Negative False_Positive]\t= {con_mat_forest_train[0]}")
print(f"[False_Negative True_Positive]]\t  {con_mat_forest_train[1]}")

print(f"Correct observations: {con_mat_forest_train[0][0] + con_mat_forest_train[1][1]}")
print(f"Incorrect observations: {con_mat_forest_train[0][1] + con_mat_forest_train[1][0]}")

print(f"Accuracy for the training set: {accuracy_score(y_train, y_pred_train_medium)*100}%")

print()

print("For the test set:")

print(f"[[True_Negative False_Positive]\t= {con_mat_forest_test[0]}")
print(f"[False_Negative True_Positive]]\t  {con_mat_forest_test[1]}")

print(f"Correct observations: {con_mat_forest_test[0][0] + con_mat_forest_test[1][1]}")
print(f"Incorrect observations: {con_mat_forest_test[0][1] + con_mat_forest_test[1][0]}")

print(f"Accuracy for the test set: {accuracy_score(y_test, y_pred_test_medium)*100}%")

For the training set:
[[True_Negative False_Positive]	= [77319  3426]
[False_Negative True_Positive]]	  [    85 107806]
Correct observations: 185125
Incorrect observations: 3511
Accuracy for the training set: 98.13874339998728%

For the test set:
[[True_Negative False_Positive]	= [19240   960]
[False_Negative True_Positive]]	  [  133 26826]
Correct observations: 46066
Incorrect observations: 1093
Accuracy for the test set: 97.68230878517356%


<i>Classification Report</i>

In [44]:
from sklearn.metrics import classification_report

print("Classification report for the training set:")

print(classification_report(y_train, y_pred_train_medium))

print()

print("Classification report for the test set:")

print(classification_report(y_test, y_pred_test_medium))

Classification report for the training set:
              precision    recall  f1-score   support

           0       1.00      0.96      0.98     80745
           1       0.97      1.00      0.98    107891

    accuracy                           0.98    188636
   macro avg       0.98      0.98      0.98    188636
weighted avg       0.98      0.98      0.98    188636


Classification report for the test set:
              precision    recall  f1-score   support

           0       0.99      0.95      0.97     20200
           1       0.97      1.00      0.98     26959

    accuracy                           0.98     47159
   macro avg       0.98      0.97      0.98     47159
weighted avg       0.98      0.98      0.98     47159



<b>e. Gaussian Naive-Baye's</b>

<i>Model building</i>

In [45]:
from sklearn.naive_bayes import GaussianNB

classifier5=GaussianNB()
classifier5.fit(X_train,y_train)

,"priors priors: array-like of shape (n_classes,), default=NonePrior probabilities of the classes. If specified, the priors are notadjusted according to the data.",None
,"var_smoothing var_smoothing: float, default=1e-9Portion of the largest variance of all features that is added tovariances for calculation stability... versionadded:: 0.20",1e-09
Name,Type,Value
"class_count_ class_count_: ndarray of shape (n_classes,)number of training samples observed in each class.","ndarray[float64](2,)","[ 80745.,107891.]"
"class_prior_ class_prior_: ndarray of shape (n_classes,)probability of each class.","ndarray[float64](2,)","[0.43,0.57]"
"classes_ classes_: ndarray of shape (n_classes,)class labels known to the classifier.","ndarray[int64](2,)","[0,1]"
epsilon_ epsilon_: floatabsolute additive value to variances.,float64,1e-09
n_features_in_ n_features_in_: intNumber of features seen during :term:`fit`... versionadded:: 0.24,int,20
"theta_ theta_: ndarray of shape (n_classes, n_features)mean of each feature per class.","ndarray[float64](2, 20)","[[ 0.56, 0.31, 0.01,..., 0. , 0.7 , 0.62], [-0.42,-0.23, 0. ,..., 0. ,-0.52,-0.47]]"
"var_ var_: ndarray of shape (n_classes, n_features)Variance of each feature per class... versionadded:: 1.0","ndarray[float64](2, 20)","[[1.43,1.49,0.01,...,0. ,1.34,1.17], [0.27,0.51,0. ,...,0. ,0.1 ,0.36]]"


<i>Predicting the values of the training and test set</i>

In [46]:
y_pred_train5=classifier5.predict(X_train)
y_pred_test5=classifier5.predict(X_test)

print("For the training set:")
print("[Actual_observations Predicted_observations]")
print(np.concatenate((y_train.reshape(len(y_train),1),y_pred_train5.reshape(len(y_pred_train5),1)),axis=1))
print()

print("For the test set:")
print("[Actual_observations Predicted_observations]")
print(np.concatenate((y_test.reshape(len(y_test),1),y_pred_test5.reshape(len(y_pred_test5),1)),axis=1))

For the training set:
[Actual_observations Predicted_observations]
[[0 1]
 [0 0]
 [1 1]
 ...
 [0 0]
 [1 1]
 [0 1]]

For the test set:
[Actual_observations Predicted_observations]
[[0 1]
 [1 1]
 [1 1]
 ...
 [0 1]
 [0 1]
 [0 1]]


<i>Accuracy of the model</i>

In [47]:
from sklearn.metrics import accuracy_score, confusion_matrix

con_mat_nb_train=confusion_matrix(y_train,y_pred_train5)
con_mat_nb_test=confusion_matrix(y_test,y_pred_test5)

print("For the training set:")
print(f"[[True_Negative False_Positive]\t= {con_mat_nb_train[0]}")
print(f"[False_Negative True_Positive]]\t  {con_mat_nb_train[1]}")
print(f"Correct observations: {con_mat_nb_train[0][0]+con_mat_nb_train[1][1]}")
print(f"Incorrect observations: {con_mat_nb_train[0][1]+con_mat_nb_train[1][0]}")
print(f"Accuracy for the training set: {accuracy_score(y_train,y_pred_train5)*100}%")
print()

print("For the test set:")
print(f"[[True_Negative False_Positive]\t= {con_mat_nb_test[0]}")
print(f"[False_Negative True_Positive]]\t  {con_mat_nb_test[1]}")
print(f"Correct observations: {con_mat_nb_test[0][0]+con_mat_nb_test[1][1]}")
print(f"Incorrect observations: {con_mat_nb_test[0][1]+con_mat_nb_test[1][0]}")
print(f"Accuracy for the test set: {accuracy_score(y_test,y_pred_test5)*100}%")

For the training set:
[[True_Negative False_Positive]	= [37691 43054]
[False_Negative True_Positive]]	  [   545 107346]
Correct observations: 145037
Incorrect observations: 43599
Accuracy for the training set: 76.88723255370131%

For the test set:
[[True_Negative False_Positive]	= [ 9426 10774]
[False_Negative True_Positive]]	  [  139 26820]
Correct observations: 36246
Incorrect observations: 10913
Accuracy for the test set: 76.85913611399732%


<i>Classification Report</i>

In [48]:
from sklearn.metrics import classification_report

print("Classification report for the training set:")
print(classification_report(y_train,y_pred_train5))
print()

print("Classification report for the test set:")
print(classification_report(y_test,y_pred_test5))

Classification report for the training set:
              precision    recall  f1-score   support

           0       0.99      0.47      0.63     80745
           1       0.71      0.99      0.83    107891

    accuracy                           0.77    188636
   macro avg       0.85      0.73      0.73    188636
weighted avg       0.83      0.77      0.75    188636


Classification report for the test set:
              precision    recall  f1-score   support

           0       0.99      0.47      0.63     20200
           1       0.71      0.99      0.83     26959

    accuracy                           0.77     47159
   macro avg       0.85      0.73      0.73     47159
weighted avg       0.83      0.77      0.75     47159



<i>Cross-validation</i>

In [49]:
from sklearn.model_selection import cross_val_score

cross_val1_nb_train=cross_val_score(classifier5,X_train,y_train,cv=10)

print("Training accuracy after cross-validation:",cross_val1_nb_train.mean()*100,"%")

Training accuracy after cross-validation: 76.88405490043672 %


# RESULTS

# Model Comparison — Phishing URL Detection

| Model | Train Accuracy | Test Accuracy | Cross-Val Accuracy (10-fold) | Precision (Test) | Recall (Test) | F1-Score (Test) |
|---|---|---|---|---|---|---|
| Logistic Regression | 85.66% | 85.60% | 85.66% | 0.86 | 0.86 | 0.85 |
| K-Nearest Neighbors (k=15) | 96.97% | 96.40% | — | 0.97 | 0.97 | 0.97 |
| Decision Tree (entropy) | 99.99% | 98.58% | 98.55% | 1.00 | 1.00 | 1.00 |
| Random Forest (n=500) | 99.99% | 99.09% | — | 1.00 | 1.00 | 1.00 |
| Gaussian Naive Bayes | 76.89% | 76.86% | 76.88% | 0.83 | 0.77 | 0.75 |

## Confusion Matrix Summary (Test Set)

| Model | True Negative | False Positive | False Negative | True Positive |
|---|---|---|---|---|
| Logistic Regression | 14,784 | 5,416 | 1,377 | 25,582 |
| K-Nearest Neighbors | 18,882 | 1,318 | 378 | 26,581 |
| Decision Tree | 19,841 | 359 | 310 | 26,649 |
| Random Forest | 19,946 | 254 | 177 | 26,782 |
| Gaussian Naive Bayes | 9,426 | 10,774 | 139 | 26,820 |

## Key Observations

- **Random Forest** performed best overall on the test set (99.09% accuracy), with the lowest combined false positive + false negative count.
- **Decision Tree** came close (98.58%), but with a slightly higher training-vs-test gap, suggesting mild overfitting compared to Random Forest.
- **KNN** gave solid results (96.40%) but is computationally expensive at prediction time compared to tree-based models.
- **Logistic Regression** and **Gaussian Naive Bayes** underperformed relative to tree-based models — likely because the decision boundary is non-linear and features have complex interactions that linear/probabilistic models can't capture as well.
- **Gaussian Naive Bayes** had the highest false positive count (10,774), meaning it incorrectly flagged many legitimate URLs as phishing — its independence assumption doesn't hold well for this feature set.

## Recommended Model
**Random Forest** is the best choice for deployment — highest test accuracy, best precision/recall balance, and more robust to overfitting than the single Decision Tree.


In [50]:
import pickle as pk

with open(r"scaler.pk","wb") as file:
    pk.dump(scaler,file)
    
with open(r"Random_Forest.pk","wb") as file:
    pk.dump(classifier4,file)

NameError: name 'classifier4' is not defined

In [ ]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

small_forest = RandomForestClassifier(
    n_estimators=200,
    max_depth=20,
    criterion="gini",
    random_state=0,
    n_jobs=-1
)

small_forest.fit(X_train, y_train)

y_pred_small = small_forest.predict(X_test)

print("Small Random Forest Test Accuracy:",
      accuracy_score(y_test, y_pred_small) * 100, "%")

Small Random Forest Test Accuracy: 99.06910663924171 %


In [ ]:
import os
import pickle as pk

with open("Random_Forest_small.pk", "wb") as file:
    pk.dump(small_forest, file)

print("Model saved successfully.")
print("Model size:", round(os.path.getsize("Random_Forest_small.pk") / (1024 * 1024), 2), "MB")

Model saved successfully.
Model size: 82.68 MB


In [ ]:
import pickle
import os

with open("Random_Forest_small.pk", "rb") as file:
    test_model = pickle.load(file)

print("Model loaded successfully.")
print("File size:", round(os.path.getsize("Random_Forest_small.pk") / (1024 * 1024), 2), "MB")

Model loaded successfully.
File size: 82.68 MB
